name: Build & deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - develop
jobs:
  gh-pages-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout `develop` branch
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      
      - name: Clean-install dependencies using Yarn
        run: |
          rm -rf node_modules
          yarn install --frozen-lockfile
        working-directory: Web

      - name: Run script
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          yarn gh-pages-deploy
        working-directory: Web
